---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: capstone
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: capstone
          image: adamol/capstone:@VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            successThreshold: 1
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
spec:
  selector:
    app: capstone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
